# New Quad

In [1]:
%matplotlib inline

from __future__ import print_function
from __future__ import division
import numpy as np
import sympy
from sympy import symbols, sin, cos, pi, simplify

## Forward Kinematics

In [27]:
def makeT(a, alpha, d, theta):
    # create a modified DH homogenious matrix
    # this is the same matrix as above
    return np.array([
        [           cos(theta),           -sin(theta),           0,             a],
        [sin(theta)*cos(alpha), cos(theta)*cos(alpha), -sin(alpha), -d*sin(alpha)],
        [sin(theta)*sin(alpha), cos(theta)*sin(alpha),  cos(alpha),  d*cos(alpha)],
        [                    0,                     0,           0,             1]
    ])

def simplifyT(tt):
    """
    This goes through each element of a matrix and tries to simplify it.
    """
    ret = []
    for row in tt:
        m = []
        for col in row:
            m.append(simplify(col))
        ret.append(m[:])
    return np.array(ret)

def subs(tt, m):
    """
    This allows you to simplify the trigonomic mess that kinematics can
    create and also substitute in some inputs in the process
    
    Yes, this is basically the same as above. I could combine these into 1
    function, but I wanted to beclearer on what I am doing.
    """
    ret = tt.copy()
    for i, row in enumerate(tt):
        for j, col in enumerate(row):
            try:
                ret[i,j] = col.subs(m)
            except:
                ret[i,j] = simplify(col)
    return ret

In [4]:
t1, t2, t3, t4 = symbols('t1 t2 t3 t4')
d2, l1, l2, l3 = symbols('d2 l1 l2 l3')

In [33]:
# a, alpha, d, theta
T1 = makeT(0, 0, 0, t1)
T2 = makeT(d2, pi/2, 0, t2)
T3 = makeT(l1, 0, 0, t3)
T4 = makeT(l2, 0, 0, t4)
T5 = makeT(l3, 0, 0, 0)

In [34]:
print('T1 = ', T1)
print('T2 = ', T2)
print('T3 = ', T3)
print('T4 = ', T4)
print('T5 = ', T5)

T1 =  [[cos(t1) -sin(t1) 0 0]
 [sin(t1) cos(t1) 0 0]
 [0 0 1 0]
 [0 0 0 1]]
T2 =  [[cos(t2) -sin(t2) 0 d2]
 [0 0 -1 0]
 [sin(t2) cos(t2) 0 0]
 [0 0 0 1]]
T3 =  [[cos(t3) -sin(t3) 0 l1]
 [sin(t3) cos(t3) 0 0]
 [0 0 1 0]
 [0 0 0 1]]
T4 =  [[cos(t4) -sin(t4) 0 l2]
 [sin(t4) cos(t4) 0 0]
 [0 0 1 0]
 [0 0 0 1]]
T5 =  [[1 0 0 l3]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [35]:
T = T1.dot(T2.dot(T3.dot(T4.dot(T5))))
print('T = ', T)

T =  [[ ((-sin(t3)*sin(t4) + cos(t3)*cos(t4))*cos(t2) - (sin(t3)*cos(t4) + sin(t4)*cos(t3))*sin(t2))*cos(t1)
  (-(-sin(t3)*sin(t4) + cos(t3)*cos(t4))*sin(t2) + (-sin(t3)*cos(t4) - sin(t4)*cos(t3))*cos(t2))*cos(t1)
  sin(t1)
  (d2 - (l3*sin(t4)*cos(t3) + (l2 + l3*cos(t4))*sin(t3))*sin(t2) + (l1 - l3*sin(t3)*sin(t4) + (l2 + l3*cos(t4))*cos(t3))*cos(t2))*cos(t1)]
 [ ((-sin(t3)*sin(t4) + cos(t3)*cos(t4))*cos(t2) - (sin(t3)*cos(t4) + sin(t4)*cos(t3))*sin(t2))*sin(t1)
  (-(-sin(t3)*sin(t4) + cos(t3)*cos(t4))*sin(t2) + (-sin(t3)*cos(t4) - sin(t4)*cos(t3))*cos(t2))*sin(t1)
  -cos(t1)
  (d2 - (l3*sin(t4)*cos(t3) + (l2 + l3*cos(t4))*sin(t3))*sin(t2) + (l1 - l3*sin(t3)*sin(t4) + (l2 + l3*cos(t4))*cos(t3))*cos(t2))*sin(t1)]
 [ (-sin(t3)*sin(t4) + cos(t3)*cos(t4))*sin(t2) + (sin(t3)*cos(t4) + sin(t4)*cos(t3))*cos(t2)
  (-sin(t3)*sin(t4) + cos(t3)*cos(t4))*cos(t2) + (-sin(t3)*cos(t4) - sin(t4)*cos(t3))*sin(t2)
  0
  (l3*sin(t4)*cos(t3) + (l2 + l3*cos(t4))*sin(t3))*cos(t2) + (l1 - l3*sin(t3)*sin(t4) 

In [36]:
Tf = simplify(T)

In [37]:
print(Tf)

[[cos(t1)*cos(t2 + t3 + t4), -sin(t2 + t3 + t4)*cos(t1), sin(t1), (d2 + l1*cos(t2) + l2*cos(t2 + t3) + l3*cos(t2 + t3 + t4))*cos(t1)], [sin(t1)*cos(t2 + t3 + t4), -sin(t1)*sin(t2 + t3 + t4), -cos(t1), (d2 + l1*cos(t2) + l2*cos(t2 + t3) + l3*cos(t2 + t3 + t4))*sin(t1)], [sin(t2 + t3 + t4), cos(t2 + t3 + t4), 0, l1*sin(t2) + l2*sin(t2 + t3) + l3*sin(t2 + t3 + t4)], [0, 0, 0, 1]]


In [38]:
print('position x: {}'.format(Tf[0,3]))
print('position y: {}'.format(Tf[1,3]))
print('position z: {}'.format(Tf[2,3]))

position x: (d2 + l1*cos(t2) + l2*cos(t2 + t3) + l3*cos(t2 + t3 + t4))*cos(t1)
position y: (d2 + l1*cos(t2) + l2*cos(t2 + t3) + l3*cos(t2 + t3 + t4))*sin(t1)
position z: l1*sin(t2) + l2*sin(t2 + t3) + l3*sin(t2 + t3 + t4)


In [54]:
from math import cos, sin, pi, atan2, sqrt, acos
def forward(t1,t2,t3,t4, degrees=True):
    d2 = 30
    l1 = 60
    l2 = 80
    l3 = 30
    
    if degrees:
        t1 *= pi/180
        t2 *= pi/180
        t3 *= pi/180
        t4 *= pi/180
        
    x = (d2 + l1*cos(t2) + l2*cos(t2 + t3) + l3*cos(t2 + t3 + t4))*cos(t1)
    y = (d2 + l1*cos(t2) + l2*cos(t2 + t3) + l3*cos(t2 + t3 + t4))*sin(t1)
    z = l1*sin(t2) + l2*sin(t2 + t3) + l3*sin(t2 + t3 + t4)
    return (x,y,z)

## Inverse Kinematics

In [61]:
def cosinelaw(a,b,c):
    # cos(g) = (a^2+b^2-c^2)/2ab
    return acos((a**2+b**2-c**2)/(2*a*b))

def inverse(x,y,z,o, degrees=True):
    d2 = 30
    l1 = 60
    l2 = 80
    l3 = 30
    t1 = atan2(y,x-d2)
    
    w = sqrt((x-d2)**2+y**2)
    j4w = w+l3*cos(o)
    j4z = z+l3*sin(o)
    r = sqrt(j4w**2+j4z**2)
    g1 = atan2(j4z,j4w)
    g2 = cosinelaw(l1,r,l2)
    t2 = g1+g2
    
    t3 = pi+cosinelaw(l1,l2,r)
    
    j2w=l1*cos(t2)
    j2z=l1*sin(t2)
    c=sqrt((w-j2w)**2+(z-j2z)**2)
    t4=pi+cosinelaw(l2,l3,c)
    
    
    if degrees:
        t1 *= 180/pi
        t2 *= 180/pi
        t3 *= 180/pi
        t4 *= 180/pi
    
    return (t1,t2,t3,t4)

In [62]:
print('forward:', forward(0,0,0,0))
print('inverse [deg]:', inverse(200,0,0,pi))

forward: (200.0, 0.0, 0.0)
inverse [deg]: (0.0, 1.5035805639717594e-15, 360.0, 360.0)


In [63]:
2*pi

6.283185307179586

In [64]:
print('forward:', forward(0,20,-110,0))
print('inverse [deg]:', inverse(5.2,0,-43.6,90))

forward: (86.3815572471545, 0.0, -89.47879140045987)
inverse [deg]: (180.0, 113.41783600363294, 182.68908020955848, 359.4867600357776)
